version: "3.2"

services:
#MariaDB Container
  db-glpi:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./mariadb.env
    restart: always
    networks:
      - glpi_nt

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "5000:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=America/Mexico_City
    restart: always
    networks:
      - glpi_nt

networks:
  glpi_nt:
    external: true
    driver: bridge